### ISSUE TITLE
Research CMS tooling

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mozilla-Learning#1]
Who / what / how frequent will changes need to be made to teach.webmaker.org?

This ticket is for researching and exploring UX around different options.

**Comment by hannahkane** [comment]
This is covered in #75, so closing this.

**Comment by toolness** [comment]
## This issue has been moved to https://github.com/toolness/test-learning-migration/issues/6
Please don't comment on it here.

**Comment by toolness** [comment]
## This issue has been moved to https://github.com/toolness/test-learning-migration/issues/7
Please don't comment on it here.

**Comment by toolness** [comment]
(Sorry about all the spam on this issue, I'm working on #807 and this is my guinea pig.)

**Comment by toolness** [comment]
<a href="https://github.com/toolness/test-learning-migration/issues/8"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/toolness/test-learning-migration/issues/8.
Please don't comment on it here.

**Comment by toolness** [comment]
<a href="https://github.com/toolness/test-learning-migration/issues/9"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/toolness/test-learning-migration/issues/9.
Please don't comment on it here.
