### ISSUE TITLE
Design badge pages for Hive Toronto privacy badges

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Mozilla-Learning#10]
As per this planning ticket: https://github.com/MozillaFoundation/plan/issues/206

* Current badge landing page template that we will use:
https://webmaker.org/badges/hive-community-member

* **Needs claim code UX.** The page design will need to be tweaked to have the user enter a claim code to earn the badge. Note that claim codes are the *only* way for users to earn these badges. (There will be no back-end assessment queue. Claim codes only.) 

* Draft copy for the page is here:  https://docs.google.com/document/d/1bPJl4ch63JOQwmq2K3CjUdjkfzo3ajZKbzIYNqEdFsI/edit?usp=sharing 

cc @smithisgeneric @simonwex @ScottDowne

**Comment by OpenMatt** [comment]
From @smithisgeneric:
* Draft copy for the page is here:  https://docs.google.com/document/d/1bPJl4ch63JOQwmq2K3CjUdjkfzo3ajZKbzIYNqEdFsI/edit?usp=sharing 

* Current badge landing page for us to re-purpose:
https://webmaker.org/badges/hive-community-member

- QUESTION: How many landing pages do we need here? One or three? (e.g. a single landing page for all 3 badges,  or should they be broken up onto 3 separate pages?)

**Comment by OpenMatt** [comment]
* NOTE: Karen reports a possible log-in related bug with webmaker.org badges pages.
* Filed here: https://github.com/mozilla/webmaker.org/issues/1229

**Comment by OpenMatt** [comment]
* This copy is in good shape -- I'll do a quick final edit and then it should be good to go.
https://docs.google.com/document/d/1bPJl4ch63JOQwmq2K3CjUdjkfzo3ajZKbzIYNqEdFsI/edit

**Comment by OpenMatt** [comment]
@smithisgeneric : in the copy, I suggested changing the name of the "Coach" badge to "Privacy Coach," for clarity. That ok?
* Also: @smithisgeneric still needs to update all the links in this copy.

**Comment by OpenMatt** [comment]
@smithisgeneric: who is the target audience for this copy? Learners, or educators? I'm wondering about the badge requirements section in particular. It reads very educator-focused right now.

**Comment by smithisgeneric** [comment]
Replying to @OpenMatt 

* Changing title from Coach to Privacy Coach is fine
* For the landing page which overviews all three badges the target is educators but without being unfriendly to learners (roughly: 75% educators / 25 % learners)
* Links will be updated as they are ready  
* A sketch for the flow with claims codes is in #11

**Comment by OpenMatt** [comment]
![hivebadgeflow](https://cloud.githubusercontent.com/assets/6931814/6132068/31b87cc0-b11e-11e4-9869-cd5e81bdfeb5.jpg)

**Comment by OpenMatt** [comment]
@iamjessklein just to be clear: what this basically means is, all that's required here design-wise is to add a field to this template https://webmaker.org/badges/hive-community-member that says:

 "Enter your claim code to earn this badge: [                ]" 
(or something like that)
![claim code mockup](https://cloud.githubusercontent.com/assets/1007376/6135094/c58ebab2-b133-11e4-8487-e76dd788d480.png)

**Comment by OpenMatt** [comment]
@iamjessklein : can you confirm that this makes sense? Don't need to start work this Heartbeat -- just want to see if we're all clear to get started once your current P1s are done.

**Comment by iamjessklein** [comment]
:+1:  got it. makes sense.

**Comment by OpenMatt** [comment]
:)

**Comment by ScottDowne** [comment]
I'm seeing some already similar implementation on webmaker.org's badge pages.

Example, if you click apply while logged in from here: https://webmaker.org/badges/hive-community-member

You get this:

![claim](https://cloud.githubusercontent.com/assets/197334/6176818/c7d42e40-b2cf-11e4-9287-86acfd0432d6.png)

And once you claim it, you see this:
![success](https://cloud.githubusercontent.com/assets/197334/6176823/cb67ca80-b2cf-11e4-98c0-590b518be1f9.png)

**Comment by OpenMatt** [comment]
* To summarize Scott's points above: 
* what we realized today is that the "enter a claim code" field *already* exists on the existing badge page template. (see: https://webmaker.org/badges/hive-community-member ) So we don't actually need to create a new template to support this -- it's already there. 
* what we do need to consider is: can Jess make potential tweaks to improve the UI of the template for *all* of our webmaker.org badge pages? Given that the "apply" button and "enter a claim code" field are quite buried right now, and not very obvious to users. 
* plus a UX question: the current badge page template allows users to *either* 1) enter a claim code *or* 2) click "Apply" and submit evidence, which is then reviewed in an assessment queue. 
* For these Hive Toronto Privacy badges, we *only* want to support (1). Not (2). Do we need a UX change here to support that? And if so: what's the easiest way to do that without breaking or having to fork the template?

**Comment by OpenMatt** [comment]
I think we can close this. We don't actually need design work here -- it's all about the build ticket. https://github.com/MozillaFoundation/Mozilla-Learning/issues/11
