### ISSUE TITLE
Leadership development : RC comes to whistler

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#14]

**Comment by hannahkane** [comment]
I think this is covered in #22 so I'm closing this for now.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/4"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/4.
Please don't comment on it here.
