### ISSUE TITLE
Leadership development:  RC's leading  the Club leaders onboarding 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#15]

**Comment by hannahkane** [comment]
I think this is covered in #23

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/5"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/5.
Please don't comment on it here.
