### ISSUE TITLE
Create plan for RC's to capture potential Club Leaders through Maker Party

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#17]
Use our messaging and narrative (from "Story of Self, Us and Now" activity), and allow for regional planning.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] TBD

**Comment by Saallen** [comment]
**Utilizing story of Self Us and Now
**Regonal planning

**Comment by hannahkane** [comment]
I think this is implied in #18

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/7"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/7.
Please don't comment on it here.
