### ISSUE TITLE
Explore teach.webmaker.org visual branding

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mozilla-Learning#2]
Assuming this iteration of teach.webmaker.org is somewhere between Webmaker styles and a potentially new Mozilla Learning brand, what would that look like? Prob. still needs to feel like it falls within or at least beside the Webmaker brand. Could just slightly tweak different palettes and imagery, for example.

I think the deliverable for this ticket should be:
* a revised color palette and 
* treatments for images and 
* sample illustrations.

@sabrinang I'm actually wondering if some of the Training branding you did last year could be a good jumping off point for this.

**Comment by hannahkane** [comment]
Don't know if this ticket also encompasses the issue of the name and the url, but wanted to leave these ideas from @hpauljohnson here:

* A possible solution is to have Mozilla Learning be the name, and "Teach the Web" be a tagline
* Another option for the url is potentially learning.mozilla.org

**Comment by cassiemc** [comment]
Filed a new issues #9 for that. Thanks @hannahkane. Let's keep this ticket to visual branding solutions, I'll update the title.

**Comment by cassiemc** [comment]
Using this guide to help design the landing page #5  ![brand-palettes-v2b](https://cloud.githubusercontent.com/assets/1186326/6136292/8159feec-b13d-11e4-8406-d0f94bf3f2f1.jpg)

**Comment by cassiemc** [comment]
You can leave feedback on this here: https://redpen.io/oadc33333ea1ac4bf3

**Comment by hannahkane** [comment]
@cassiemc - wondering if we can close this for now.

**Comment by cassiemc** [comment]
Yes! Got what we needed from it.
