### ISSUE TITLE
Create calendar of TTW talks topics

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#25]
The topic list should complement the curriculum modules.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] List of talk topics
 - [ ] Confirmed guest speakers
 - [ ] Publish calendar of upcoming talks on teach site

**Comment by Saallen** [comment]
Adding @LucyeoH  into this issue. 
We can flex this out in the coming weeks

**Comment by LauraHilliger** [comment]
check out issue 60, perhaps a centralized calendar is in order?

**Comment by Saallen** [comment]
Agreed. I will close this issue.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/15"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/15.
Please don't comment on it here.
