### ISSUE TITLE
User-test wireframes with users outside the mozilla network

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mozilla-Learning#3]
@hannahkane mentioned that it could be helpful to have insights from users who have no prior experience with Mozilla. Could we retest some of the wireframes – from https://marvelapp.com/11ji896#2375127 and https://marvelapp.com/b0ah39#2378718 – with a few new users?

FYI:
**HK'S User testing analysis from Round 1:**
Doc: https://docs.google.com/a/mozillafoundation.org/document/d/1O5XgvrTDShvipos_Ks1GeKLvewvaoBFMCQwtz0dE1Nk/edit
Presentation: https://docs.google.com/a/mozilla.com/presentation/d/1T2nhwdPjfWRNSK1FRg_yAr9Tit7TSN4GuwTfISMy3jc/edit?usp=sharing

**Comment by hannahkane** [comment]
Probably not going to do this at this point, though we will plan to conduct regular testing with people outside of our immediate network. See #61
