### ISSUE TITLE
2015 End of Year: What does success look like from each stream?

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#31]
**Leadership development
**Online Platform
** Curriculum
** Partners
** Mobilizing

**Comment by hannahkane** [comment]
Incorporating this into #32

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/21"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/21.
Please don't comment on it here.
