### ISSUE TITLE
Update wiki with work week decisions

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#32]
Wiki pages to write:
- [x] Insights from other models
- [x] Our POV
- [x] Our allies/audience
- [x] Messaging/narrative (recalling the the storytelling exercise we did at the work week)
- [x] Naming
- [x] Job descriptions
- [x] Metrics
- [ ] Calendar of milestones and quarterly deliverables
- [ ] What does success look like for each swimlane (i.e. Leadership development, online platform, curriculum, partners, mobilizing)

Add'l tasks:
- [ ] Write blog post highlighting and pointing to all of the above

**Comment by hannahkane** [comment]
Who should be responsible for each of these pieces? @thornet, any suggesions?

**Comment by thornet** [comment]
I'll take this one. Have updated the checklist slightly.

**Comment by Saallen** [comment]
Created a timeline around the basic points we added to our Roadmap etherpad 

See timeine: [https://docs.google.com/a/mozilla.com/spreadsheets/d/1FZk_0-zAcjF0nc7fa3EK7QfVVDgRAhMoOuCoxsVR4Ts/edit?usp=sharing]

Highlights some gaps in our issues and timing in particular for curriculum.

**Comment by thornet** [comment]
Published: http://mozilla.github.io/webmaker-curriculum/about

**Comment by Saallen** [comment]
Updated the Gaaaant chart. :eyes:

**Comment by thornet** [comment]
added program update to wiki: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs

Regular meeting scheduled with @Saallen @amirad @ldecoursy @hannahkane & Simona to review roadmap and Github tickets.

**Comment by thornet** [comment]
Meeting today to review Gant chart: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1FZk_0-zAcjF0nc7fa3EK7QfVVDgRAhMoOuCoxsVR4Ts/edit#gid=0

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/22"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/22.
Please don't comment on it here.
