### ISSUE TITLE
Schedule work week follow-up meetings

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozilla-Learning#34]
- [x] Schedule partners criteria meeting w Ben and An-me
- [x] Schedule M.P clarity meeting w Amira, Paul and Claw
- [x] Schedule metrics clarity meeting w Claw, Adam
- [x] Write up results of both meetings and put into a blog or wiki

**Comment by thornet** [comment]
Met with @benrito in NYC to discuss the partner criteria. We're on the same page, with good insights on how to develop curriculum modules for specific partners and how the R.C. structure can absorb partners' staff. 

Have a meeting on Wed. with An-Me to review the same.

**Comment by thornet** [comment]
Updated checklist to include follow-up with Adam re: metrics.

**Comment by thornet** [comment]
@amirad can report on the MP meeting. 

Metrics decisions: http://mozilla.github.io/webmaker-curriculum/about/#success

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/24"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/24.
Please don't comment on it here.
