### ISSUE TITLE
Design homepage for teach.webmaker.org

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mozilla-Learning#5]
Kickoff notes are here: https://etherpad.mozilla.org/teach285

### RESOURCES:

**Teach product roadmap:**
https://wiki.mozilla.org/Learning/Networks/Product-Roadmap

**Interactive wireframes:**
performed better: https://marvelapp.com/11ji896#2375127
https://marvelapp.com/b0ah39#2378718

**Full wireframes redpen:**
https://redpen.io/p/tcd5fbcae44ba63df9

**HK'S User testing analysis:**
Doc: https://docs.google.com/a/mozillafoundation.org/document/d/1O5XgvrTDShvipos_Ks1GeKLvewvaoBFMCQwtz0dE1Nk/edit
Presentation: https://docs.google.com/a/mozilla.com/presentation/d/1T2nhwdPjfWRNSK1FRg_yAr9Tit7TSN4GuwTfISMy3jc/edit?usp=sharing

### Key insights from user testing so far: ###
* mentors want to see other mentors; find people easily
* valuable to see both full size curriculum _and_ bite-sized activities
* search is important; ppl will generally know what they're looking for
* re. clubs – people care about comprehensive material, not necessarily location (could be bias here)
* "Do you want to get involved? Here's how to do it." (easy to jump into mentor pathways)
* Happy side effect: Tools are de-emphasized; activities / content are the focus

 ### Key questions: ###
* Will we separate Audiences A & B (educators outside our network vs. contributors already within [hives, mdn, etc])
* What kind of social network are we? LinkedIn vs. Quora vs. Twitter?
* What is the best content we already have for activities and curriculum? [This is what's being tested with the Q1 pilots, right?]

**Comment by hannahkane** [comment]
I want to add this to the current milestone, but I don't seem to be able to add milestones to this repo. @simonwex , please hlep!

**Comment by davidascher** [comment]
You should have the right to do so at this point @hannahkane -- check https://github.com/MozillaFoundation/hannah-barbera/milestones

**Comment by cassiemc** [comment]
First draft: 
![teach-v3](https://cloud.githubusercontent.com/assets/1186326/6139920/77b1d08c-b15f-11e4-89d6-bc4a2cc1c55c.jpg)

Can give feedback here: https://redpen.io/pub30ddf619bc2bcf3

**Comment by hannahkane** [comment]
Thanks, @cassiemc. This is great. I'll leave specific feedback/questions on the redpen, and invite @thornet @amirad @ldecoursy and @claw to do the same.

Question: should we be leaving feedback just on the page structure, or also the visual design elements?

Thanks!

**Comment by cassiemc** [comment]
Definitely feel like I'm flying blind so any and all feedback welcome at this point. Thanks @hannahkane

**Comment by hannahkane** [comment]
Added my comments to the newest designs: https://redpen.io/pub30ddf619bc2bcf3

In addition to the people above (most of whom are out of the office), I'd also appreciate feedback from @thisandagain, @OpenMatt, and @edrushka.

**Comment by cassiemc** [comment]
Have updated the redpen with the latest. I think we should move to close this issue up if there are no other significant design changes. 

Can get a design R? from @iamjessklein? https://redpen.io/pub30ddf619bc2bcf3

**Comment by edrushka** [comment]
@hannahkane @cassiemc happy to help with feedback on copy but I can't tell what's placeholder. Can we meet briefly to discuss where you're at with words? Would be good to include Kevin (don't think he's on Github yet) as well.

**Comment by cassiemc** [comment]
@hannahkane @edrushka Make sense to file copy review as a followup ticket?

**Comment by edrushka** [comment]
wfm!

**Comment by hannahkane** [comment]
Added #63 as a reminder to do a thorough copy review of the whole site a little later in the process.

So, all that remains for this is an R from @iamjessklein, when she's able.

**Comment by edrushka** [comment]
@KevZawacki here's the design ticket for the (upcoming) teach.webmaker.org page. We'll do copy review in a separate ticket, but this should give you some context.

**Comment by cassiemc** [comment]
This is moving forward in the build, so lets file any additional issues as followups.
Here's the final design: https://redpen.io/pub30ddf619bc2bcf3
Here's the design with the grid overlay: https://redpen.io/fk3c9fa74d54f34dee

Also attaching final design here: 
![teach-v8](https://cloud.githubusercontent.com/assets/1186326/6271665/31e33118-b830-11e4-99b1-2a39e123a88c.jpg)
