### ISSUE TITLE
Change repo name to Mozilla-Learning?

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Mozilla-Learning#7]
As much as I love Scooby Doo and the Flintstones, I'm wondering if this repo name could be made slightly more descriptive. :) Perhaps Mozilla-Learning?

I don't know if it's possible to change a repo name, and, if it's not, I don't seem to have permissions to create a new repo within MozillaFoundation.

Please advise, @simonwex. :)

**Comment by davidascher** [comment]
done
