### ISSUE TITLE
Draft Welcome emails for new Teach site members, Club Leaders, and "interested" Club Leaders

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Mozilla-Learning#82]
### RACI
* Owner: @hannahkane 
* Decision Maker: @thornet 
* Copy Lead: @amirad 
* Consulted: @ldecoursy @LucyeoH 

We'll want to set up three auto-emails, and we need copy for each.

1) Welcome email a user gets upon signing up through the Teach site. 
* needs to include basic Wm stuff, since they’re also signing up for Webmaker
* needs to offer a good first step - maybe “Check out the Teaching Activities”?

2) Welcome email a user gets upon adding their Club to the map.
* Thanks for adding your Club!
* Reminder about “Tips for running your Club” page
* An organizer will be in touch with you shortly

3) Email a user gets upon indicating their interest in starting a Club.
* Thanks for your interest
* We'll be in touch shortly

**Comment by amirad** [comment]
Who are these emails from? Nameless? The team? Someone specific?

**Comment by hannahkane** [comment]
They'd be system-delivered, but I'd vote for having them signed by someone specific. Maybe you or @thornet?

/cc @chrislarry33

**Comment by davidascher** [comment]
Flag that this is what's called "transactional emails" I presume (you sign
up, you get an email, as opposed to you're on a mailing list, you get
emails).  Good for @jbuck and @simonwex to know and think about as we're
building that capacity up elsewhere already.

L10n also likely impactful here.  Are the emails from regional leaders?
Just from e.g. @thornet but translated?

**Comment by hannahkane** [comment]
Yes, transactional. For v1, they likely won't be from regional coordinators, they'll all be from the same staff person. Scheduled to discuss v1 l10n reqs tomorrow morning.

**Comment by amirad** [comment]
Did a rough cut here: https://teach.etherpad.mozilla.org/clubtransactionalemails 

@hannahkane @ldecoursy @thornet can you edit pls!

**Comment by thornet** [comment]
Thanks for these! Made some edits in the etherpad.

**Comment by ldecoursy** [comment]
Also added comments - thanks!

**Comment by hannahkane** [comment]
Also added edits. Overarching suggestion is to choose one CTA per email. @thornet, @ldecoursy, and @LucyeoH - if you agree, can you weigh in on which is the most important CTA for each email?

I also added some subject line ideas. Could definitely use some love. :)

**Comment by LucyeoH** [comment]
Hey tried pulling out some CTA's. @hannahkane Was wondering how login is going to work on this site? If we need them to create a specific login for the site or will it be the same as Webmaker? Also should we have any of the CTA's be to "make an account" if they haven't already?

**Comment by hannahkane** [comment]
Thanks for clarifying the CTAs, @LucyeoH. 

Users will log in to the site - the devs will determine this heartbeat whether it's a shared sign-on with Webmaker or not. The goal is that eventually it is (and it likely will be from the beginning).

Everyone who receives one of these emails will have an account, by definition (email #1 is what they receive after creating an account, and emails #2 and #3 will require an account).

A future iteration will create the concept of a Mentor Profile, and that will likely become a primary CTA for email #1.

Going to close this out now. I think we're good on the copy. Thanks!
