### ISSUE TITLE
Clubs curriculum: publish two "Participatiing on the Web" activities. 

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/Mozilla-Learning#87]
Web Chef: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session03-chef.html
Story of Us: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session03-storyofus.html

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/38"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/38.
Please don't comment on it here.
