### ISSUE TITLE
Create overview of curriculum in development

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/Mozilla-Learning#88]
We need a page that shows what modules we're working on and their status

Made this: http://mozilla.github.io/webmaker-curriculum/

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/39"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/39.
Please don't comment on it here.
