### ISSUE TITLE
Rio: localize initial report about Rio de Janeiro LAN houses

### ISSUE THREAD

**Issue by soapdog** [MozillaFoundation/Mozilla-Learning#95]
Localize the report made by Laura into Brazilian Portuguese. I have InDesign here and can do it once I have access to the original file.

**Comment by ldecoursy** [comment]
Hi @soapdog Can you clarify, are you referring to the field research from Kenya? https://blog.mozilla.org/m4d/2015/02/03/webmakers-field-research-report-from-kenya/

If so, would you mind filing in the webmaker.org repo? https://github.com/mozilla/webmaker.org/issues

Thanks!

**Comment by soapdog** [comment]
Hi @ldecoursy. I am referring to the initial report made about Rio de Janeiro, not the one about Kenya. Thanks a lot for sending me the Kenya related info though. That report is great.

**Comment by ldecoursy** [comment]
Closing this here - refiled in Research repo https://github.com/MozillaFoundation/research/issues/17

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/46"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/46.
Please don't comment on it here.
